### ISSUE TITLE
branding

### ISSUE THREAD

**Issue by e3krisztian** [e3krisztian/lib#20]
The current name `lib` from `librarian` fits quite well, but it is widely used in programming with another meaning.

This project definitely has some similarity how books and periodicals are created with their identifiers being ISBN, ISSN.

The project name should imply one or more of:

- having resilience to manipulation
- having stable connections
- being peer to peer
- related to data
- similarity with press business
- relaxed workflow

**Comment by krisztianfekete** [comment]
candidates:
- hare (from HAck REcord - trail of data hacks)
- hackpack
- toadstool
- datapress

any more?

**Comment by krisztianfekete** [comment]
- Santa's Factory
- Santa's Workshop

**Comment by krisztianfekete** [comment]
use [WordNet](http://wordnetweb.princeton.edu/perl/webwn) for discovering potential names

**Comment by e3krisztian** [comment]
decision: bead
